[package]
name = "my_rs_ideas_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["ambassador-where"]
ambassador-where = []

[dependencies]
ambassador = "0.3.5"
async-std = "1.12.0"
delegate = "0.8.0"
derive_builder = "0.11.2"
serde = {version = "1.0.144", default-features = false, features = ["alloc", "derive"]}
serde_json = "1.0.85"
