[package]
name = 'my_rs_ideas_playground'
edition = '2021'
version = '0.1.0'

[package.metadata]
last-modified-system-time = 1668555857

[dependencies]
ambassador = '0.3.5'
async-std = '1.12.0'
delegate = '0.8.0'
derive_builder = '0.11.2'
locate-cargo-manifest = '0.2.2'
serde_json = '1.0.85'

[dependencies.cargo_toml]
version = '0.13.0'
features = []
optional = true

[dependencies.serde]
version = '1.0.144'
features = [
    'alloc',
    'derive',
]
default-features = false

[dependencies.toml]
version = '0.5.8'
features = ['preserve_order']

[features]
ambassador-where = []
cargo-metadata = ['cargo_toml']
default = []
toml-config = []
